config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'post_images#index'

  resources :post_images, only: [:new, :create, :index, :show, :destroy] do
  	resource :favorites, only: [:create, :destroy]
  	resource :post_comments, only: [:create, :destroy]
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :post_image
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
belongs_to :user
belongs_to :post_image
end

app/models/post_image.rb
class PostImage < ApplicationRecord
belongs_to :user
attachment :image

has_many :favorites, dependent: :destroy
has_many :post_comments, dependent: :destroy

validates :shop_name, presence: true
validates :image, presence: true

def favorited_by?(user)
	favorites.where(user_id: user.id).exists?
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :configure_permitted_parameters, if: :devise_controller?
before_action :authenticate_user!
protected

def configure_permitted_parameters
	devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		post_image = PostImage.find(params[:post_image_id])
		favorite = current_user.favorites.new(post_image_id: post_image.id)
		favorite.save
		redirect_to post_image_path(post_image)
	end

	def destroy
		post_image = PostImage.find(params[:post_image_id])
		favorite = current_user.favorites.find_by(post_image_id: post_image.id)
		favorite.destroy
		redirect_to post_image_path(post_image)
	end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
def create
	post_image = PostImage.find(params[:post_image_id])
	comment = current_user.post_comments.new(post_comment_params)
	comment.post_image_id = post_image.id
	comment.save
	redirect_to post_image_path(post_image)
end

private
def post_comment_params
	params.require(:post_comment).permit(:user_id, :post_image_id, :comment)
end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController

def new
	@post_image = PostImage.new
end

def create
	@post_image = PostImage.new(post_image_params)
	@post_image.user_id = current_user.id
	if @post_image.save
	redirect_to post_images_path
else
	render :new
end
end

def index
	@post_images = PostImage.page(params[:page]).reverse_order
end

def show
	@post_image = PostImage.find(params[:id])
	@post_comment = PostComment.new
end

def destroy
	@post_image = PostImage.find(params[:id])
	@post_image.destroy
	redirect_to post_images_path
end

private
def post_image_params
	params.require(:post_image).permit(:shop_name, :image, :caption)
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@post_images = @user.post_images.page(params[:page]).reverse_order
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	@user.update(user_params)
  	redirect_to user_pat(@user.id)
  end

  private
  def user_params
  	params.require(:user).permit(:name, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meshiterro</title>
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,600,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
  </head> 

  <body>

    <div class="header" id="header">
      <nav class="navbar navbar-main navbar-shadow" role="navigation" id="slide-nav">
        <div class="container relative">
          <div class="navbar-header">
            <a class="navbar-logo" href="/">
              <%= image_tag('logo.png') %>
            </a>
   
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div id="slidemenu">
            <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
              <% if user_signed_in? %>
	      	  	<li class="">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
              <li class="">
                <%= link_to "投稿フォーム", new_post_image_path %>
              </li>
              <li clas="">
                <%= link_to 'マイページ', user_path(current_user.id) %>
              </li>
              <% else %>
              <li class="">
                <%= link_to "新規登録", new_user_session_path %>
              </li>
              <li class="">
                <%= link_to "ログイン", new_user_session_path %>
              </li>
                <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </div>
  
    <%= yield %>

   <footer class="footer style-2">
      <div class="container">
        <div class="row">
          <div class="col-md-3">
            <div class="col">
              <br>
              <p class="no-margin" style="font-size: 11px;">
              <br>
              善良な市民同士で無差別に食欲を煽るSNS
          </p>
              <%= image_tag('logo-white.png') %>
              
            </div>
          </div>
          <div class="col-md-2">
            <div class="col">
              <h4>Link</h4>
              <ul>
                <li>
                  <a href="" title="About">会社概要</a>
                </li>
                <li>
                  <a href="" title="License informations">プライバシーポリシー</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </footer>
    
  </body>
</html>

app/views/post_images/_list.html.erb
<section class="sct-color-1 slice">
  <div class="container-fluid masonry-container">
    <div class="row">
      <div class="col-md-8 col-sm-offset-2">
        <div class="masonry-wrapper-cols">
          <div class="masonry-gutter"></div>

          <% post_images.each do |post_image| %>

          <div class="masonry-block">
            <div class="block block-image v1">

              <div class="block-image">
                <div class="view view-first">
                  <%= link_to post_image_path(post_image.id) do %>
                  <%= attachment_image_tag post_image, :image %>
                  <% end %>
                </div>
              </div>

              <div class="block-content">
                <%= image_tag ('images/sample-author1.jpg', class: "img-circle pull-left profile-thumb") %>
                <h3 class="block-title">
                  <%= link_to post_image_path(post_image.id) do %>
                  <i class="fa fa-map-marker"></i><%= post_image.shop_name %>
                  <% end %>
                </h3>
                <p><%= post_image.caption %></p>
                <ul class="inline-meta">
                  <li>By
                    <%= post_image.user.name %>
                  </li>
                  <li>
                    <a href="#">コメント</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <% end %>
          <%= paginate post_images, class:"pagenate" %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/post_images/index.html.erb
<%= render 'post_images/list', post_images:@post_images %>


app/views/post_images/new.html.erb
<section class="slice sct-color-1">
  <div class="container">
    <div class="row">
      <div class="col-md-12">

        <div class="row">
          <div class="col-md-6 col-md-offset-3 post_image_form">
            <div class="section-title-wrapper style-1 v1">
              <h3 class="section-title section-title-sm left">
                <span>画像投稿フォーム</span>
              </h3>
            </div>

            <%= form_for(@post_image, url: post_images_path) do |f| %>
            <% if @post_image.errors.any? %>
            <div id="error_explanation">
              <h2><%= @post_image.errors.count %>件のエラーが発生しました。</h2>
              <ul>
                <% @post_image.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
              </ul>
            </div>
            <% end %>

              <div class="row">
                <div class="col-sm-12">
                 <%= f.attachment_field :image %>
                </div>
              </div><br>
              
              <div class="row">
                <div class="col-sm-6">
                  <div class="form-group has-icon">
                    <label class="control-label sr-only">ショップ名</label>
                    <%= f.text_field :shop_name, class:"form-control", placeholder:"ショップ名" %>
                    <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
                  </div>
                </div>
                <div class="col-sm-6">
                </div>
              </div>

              <div class="row">
                <div class="col-sm-12">
                  <%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"コメントここに" %>
                </div>
              </div>
              <hr>
              <%= f.submit "送信", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
              <% end %>

             
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/post_images/show.html.erb
<section class="sct-color-1 slice">
  <div class="container">
    <div class="row">
      <div class="col-md-12 post_images_container">
        <div class="post-item">

          <div class="post-meta-top">
            <div class="post-image">
             <%= attachment_image_tag@post_image, :image %>
            </div>
          </div>

          <div class="post-content">
            <h2 class="post-title"><%= @post_image.shop_name %></h2>
            <ul class="meta-info-cells v4 float-wrapper">
              <li>
                <i class="fa fa-user"></i>By
                <a href="#">
                  <%= @post_image.user.name %></a>
              </li>
              <li>
                <i class="fa fa-calendar"></i><%= @post_image.created_at.strftime('%Y/%m/%d') %>
              </li>

              <% if @post_image.favorited_by?(current_user) %>
              <li>
                <%= link_to post_image_favorites_path(@post_image), method: :delete do %>
                <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                <%= @post_image.favorites.count %>いいね
                <% end %>
              </li>
              <% else %>
              <li>
                <%= link_to post_image_favorites_path(@post_image), method: :post do %>
                <i class="fa fa-heart-o" aria-hidden="true"></i>
                <%= @post_image.favorites.count %>いいね
                <% end %>
              </li>
              <% end %>

              <li>
                <i class="fa fa-comment"></i>
                <a href="#comments"><%= @post_image.post_comments.count %></a>
              </li>
              <li>
                <% if @post_image.user == current_user %>
                <%= link_to "削除", post_image_path(@post_image), method: :delete %>
                <% end %>
              </li>
            </ul>
            <div class="post-content-inner mt-20">
              <p><%= @post_image.caption %></p>
            </div>
          </div>

          <div class="comment-list bt style-2" id="comments">
            <div class="float-wrapper">
              <h2 class="comment-count"><%= @post_image.post_comments.count %>件コメント</h2>
            </div>
            <ol>
               <%= @post_image.post_comments.each do |post_comment| %>
              <li class="comment">
                <div class="comment-body bb">
                  <div class="comment-avatar">
                    <div class="avatar">
                      <%= attachment_image_tag post_comment.user, :profile_image_id, :fill, 60, 60, fallback: "no_image.jpg" %>
                      
                    </div>
                  </div>
                  <div class="comment-text">
                    <div class="comment-author clearfix">
                      <a href="#"><%= post_comment.user.name %></a>
                      <span class="comment-meta">
                        <span class="comment-date"><%= post_comment.created_at.strftime('%Y/%m/%d') %></span>
                      </span>
                    </div>
                    <div class="comment-entry"><%= post_comment.comment %></div>
                  </div>
                </div>
              </li>
              <% end %>
            </ol>
          </div>
          <hr>

          <!-- Add comment section -->
          <div class="section-title-wrapper style-1 v1 mt-30" id="divAddComment">
            <h3 class="section-title left">
              <span>コメント</span>
            </h3>
          </div>
          <%= form_for [@post_image, @post_comment] do |f| %>
            <div class="row">
              <div class="col-sm-12">
                <%= f.text_field :comment, rows:'5', class: "form-controll", placeholder:"コメントをここに" %>
              </div>
            </div>
            <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/edit.html.erb
<div class="body-wrap">
	<div id="st-container" class="st-container">
	<div class="st-pusher">
		<div class="st-content">
			<div class="st-content-inner">
				<section class="slice slice-lg sct-color-1">
					<div class="container">
						<div class="row">
							<div class="col-md-4 col-md-offset-4">
								<div class="form-user style-1 rounded has-shadow-1">
									<div class="form-header text-center">
										<h2 class="form-header-title">プロフィール編集</h2>
									</div>
									<div class="form-body">
										<%= form_for(@user) do |f| %>
										<div class="form-group has-icon">
											<label class="control-label sr-only" for="inputEmail">Name</label>
											<%= f.text_field :name,autofocus: true, class:"form-control", id:"inputEmail", placeholder:"名前"%>
											<span class="fa fauser form-control-icon" aria-hidden="true"></span>
										</div>

										<div class="form-group has-icon">
											<div class="user-edit-image">
												<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" %>
											</div>
											<label class="control-label sr-only" for="inputEmail">ProfileImage</label>
											<%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
										</div>
										
										<%= f.submit "変更を保存", clss:"btn btn-lg btn-block btn-base-1 mt-20" %>
										<% end %>

									</div>
								</div>
							</div>
						</div>
					</div>
				</section>
			</div>
		</div>
	</div>
</div>
</div>

app/views/users/show.html.erb
<div class="profile-container">
  <h3 class="profile-name"><%= @user.name %></h3>
  <%= attachment_image_tag@user, :profile_image_id, :fill, 100, 100,format:"jpeg", class:"img-circle pull-left profile-img", fallback: "no_image.jpg" %>
  <% if @user.id == current_user.id %>
  <p><%= link_to "プロフィール編集",edit_user_path(@user), class:"pull-right" %></p>
  <% end %>
</div>

<section class="sct-color-1 slice">
  <div class="container-fluid masonry-container">
    <div class="row">
      <div class="col-md-8 col-sm-offset-2">
        <div class="masonry-wrapper-cols">
          <div class="masonry-gutter"></div>

          <% @post_images.each do |post_image| %>

          <div class="masonry-block">
            <div class="block block-image v1">

              <div class="block-image">
                <div class="view view-first">
                  <%= link_to post_image_path(post_image.id) do %>
                  <%= attachment_image_tag post_image, :image %>
                  <% end %>
                </div>
              </div>

              <div class="block-content">
                <%= image_tag('images/sample-author1.jpg', class: "img-circle pull-left profile-thumb") %>
                <h3 class="block-title">
                  <%= link_to post_image_path(post_image.id) do %>
                  <i class="fa fa-map-marker"></i><%= post_image.shop_name %>
                  <% end %>
                </h3>
                <p><%= post_image.caption %></p>
                <ul class="inline-meta">
                  <li>By
                    <%= post_image.user.name %>
                  </li>
                  <li>
                    <a href="#">コメント</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <% end %>
          <%= paginate @post_images, class:"pagenate" %>
        </div>
      </div>
    </div>
  </div>
</section>